# Generated by Django 5.2.12 on 2026-03-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='library_music/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='music_thumbs/')),
            ],
        ),
    ]
