# Generated by Django 5.2.12 on 2026-03-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_musiclibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='music',
        ),
        migrations.AddField(
            model_name='story',
            name='music_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
