# Generated by Django 5.2.12 on 2026-03-24 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_callsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callsession',
            old_name='timestamp',
            new_name='last_seen',
        ),
    ]
