# Generated by Django 5.2.12 on 2026-03-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_last_seen_callsession_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
